# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
env:
  IMAGE_NAME: mr_gibbs
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build tags
        id: build_tags
        run: |
          DOCKER_IMAGE=name/app
          VERSION=noop
          VER="0.6"
          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$VER"
          elif [ "${{ github.event_name }}" = "pr" ]; then
            TAGS="$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')-${GITHUB_SHA:0:7}"
          echo ::set-output name=tags::${TAGS}
          
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.build_tags.outputs.tags }}
          push: true
